### ISSUE TITLE
Plugin doesnt see Tile label

### ISSUE THREAD

**Issue by fforregs** [marcusolsson/grafana-treemap-panel#14]
Grafana v7.4.3, MySQL DataSource. 
I made simple test select, like this: ```select  dat.time, dat.metric, dat.value from (select now() as "time", "fgf" as "metric", 31300 as "value") as dat```
but plugin doesnt see label field.
See the picture:
![image](https://user-images.githubusercontent.com/9361966/110108740-9d859380-7dbd-11eb-80c7-970a3f6aa01a.png)

**Comment by marcusolsson** [comment]
The plugin requires the field used for labels to be of type string. You can check what types are returned by your data source in the panel inspector:

![Screenshot 2021-03-05 at 12 29 24@2x](https://user-images.githubusercontent.com/8396880/110110289-e124d100-7dae-11eb-9e99-83b74acde219.png)

![Screenshot 2021-03-05 at 12 29 14@2x](https://user-images.githubusercontent.com/8396880/110110327-f4d03780-7dae-11eb-82d8-a1bdc9b2a06a.png)

You may also need to set **Format as** to **Table**.

**Comment by fforregs** [comment]
> You may also need to set Format as to Table.
Thank yot! This work for me!
