### ISSUE TITLE
Treemap visible only to authenticated users

### ISSUE THREAD

**Issue by tsmagnum** [marcusolsson/grafana-treemap-panel#15]
Hello, I used your plugin to create a treemap, but only the authenticated users are able to visualize it.

I'd like to build a dashboard available to guest (e.g. not authenticated) users.

Not authenticated users get a "Error loading: marcusolsson-treemap-panel" in the panel, while other plugins show correctly their data.

I'm using Grafana 7.4.3 on Ubuntu 20.04.

Thanks.

![Error](https://user-images.githubusercontent.com/65031947/111062406-d520c980-84a8-11eb-9e8a-95b3778f3852.png)

**Comment by marcusolsson** [comment]
Hi, another user has reported this on one of my other plugins. 

TL;DR: If you `hide_version` to `true`, the plugin don't know what features of Grafana it can use. 

Read more here: https://github.com/marcusolsson/grafana-hourly-heatmap-panel/issues/21#issuecomment-792542329

**Comment by tsmagnum** [comment]
Hi, thanks for your answer.

I'm going to modify the configuration accordingly.
