### ISSUE TITLE
Size and colour by different values

### ISSUE THREAD

**Issue by SergeyKuzmitskiy** [marcusolsson/grafana-treemap-panel#32]
Thanks for nice plugin.
We have an issue when trying to configure size of rectangles and colour by different values. Whan value is the same all works:
![image](https://user-images.githubusercontent.com/34037208/144566626-85fc6ef0-7c00-452b-aa8b-dec7e07101bd.png)
For different values it breaks:
![image](https://user-images.githubusercontent.com/34037208/144566920-7dfbd68f-3696-4888-9509-7fd17f61d741.png)

**Comment by marcusolsson** [comment]
Looks like a bug (or usability issue).

Would you be able to share the Data Frame structure from the Query Inspector?

**Comment by SergeyKuzmitskiy** [comment]
Thanks for point in right direction. For two queries we should use transform -> join to get result.
All working now!
