### ISSUE TITLE
Error seen when trying to use treemap plugin with docker image grafana:latest

### ISSUE THREAD

**Issue by RobertEgan** [marcusolsson/grafana-treemap-panel#7]
Reproduction Steps:
* Use grafana base image grafana/grafana:latest
* Install grafana-treemap-panal 
** RUN grafana-cli plugins install marcusolsson-treemap-panel
** - GF_INSTALL_PLUGINS: marcusolsson-treemap-panel
* Configure a data source
EXPECTED: Tree Map renders. Functions as expected in grafana/grafana:7.2.2
![image](https://user-images.githubusercontent.com/4335171/98696688-19a52880-2342-11eb-91ea-959cbfa39404.png)
ACTUAL: An error is seen in the treemap panal. Broken in grafana/grafana:7.3.0
![image](https://user-images.githubusercontent.com/4335171/98696147-705e3280-2341-11eb-9ccf-aea85eb2715b.png)
![image](https://user-images.githubusercontent.com/4335171/98696247-8cfa6a80-2341-11eb-9c09-46ebddf6a6e5.png)

**Comment by basroovers** [comment]
Seeing the same thing here. Using Grafana 7.3.1.

**Comment by R-Studio** [comment]
Seeing the same thing here. Using Grafana 7.3.2.

**Comment by marcusolsson** [comment]
Thanks for letting me know! I'll look into this!

**Comment by marcusolsson** [comment]
Looks like one of the plugin APIs for color palettes changed in 7.3. Most likely related to the recently introduced color scheme support. 

I've published a new version (0.6.0) that makes use of the new color scheme feature. This means that the plugin no longer manages the color scheme itself, but merely uses the colors selected in the field options.

It also means that the latest version (0.6.0) isn't backwards compatible with earlier versions of Grafana. There might be a way to do a fallback if you're running on an older version, but for now, hopefully this will make it usable for 7.3.

Thanks all of you for reporting (and confirming) this issue! Let me know if you experience any issues with the new version.

**Comment by R-Studio** [comment]
@marcusolsson thanks for the new version (0.6.0). Its working for me! 👍
